filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /json_logs/*.json

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat.log
  rotateeverybytes: 10485760 # = 10MB
  keepfiles: 7
